route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            channel: '#business'
            api_url: 'https://hooks.slack.com/services/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'